In [76]:
#Import

import pandas as pd
import numpy as np

In [77]:
#Preparo el dataset de training

df_training = pd.read_csv('./../data/diamons_clean.csv')
df_training.head()

   price  carat  depth  table     x     y     z   city clarity color      cut
0   4268   1.21   62.4   58.0  6.83  6.79  4.25  Dubai     VS2     J  Premium
1   3513   1.02   61.6   58.0  6.40  6.35  3.93  Dubai     VS2     J  Premium
2   1792   0.77   62.3   58.0  5.86  5.80  3.63  Dubai     VS2     J  Premium
3   7553   1.51   59.6   60.0  7.58  7.48  4.49  Dubai     VS2     J  Premium
4   1176   0.57   60.2   62.0  5.40  5.33  3.23  Dubai     VS2     J  Premium

In [78]:
#Elimino "city"

df_training = df_training.drop(columns='city')
df_training[:2]

   price  carat  depth  table     x     y     z clarity color      cut
0   4268   1.21   62.4   58.0  6.83  6.79  4.25     VS2     J  Premium
1   3513   1.02   61.6   58.0  6.40  6.35  3.93     VS2     J  Premium

In [79]:
#Preparo el dataset con nuevos features

df_training['xy'] = df_training['x']/df_training['y']
df_training['xz'] = df_training['x']/df_training['z']
df_training['zy'] = df_training['z']/df_training['y']
df_training['table_depth'] = df_training['table']/df_training['depth']
df_training['carat/dimensons'] = df_training ['carat'] / (df_training['x']* df_training['y'] * df_training['z'])
df_training[:2]

,price,carat,depth,table,x,y,z,clarity,color,cut,xy,xz,zy,table_depth,carat/dimensons
0,4268,1.21,62.4,58.0,6.83,6.79,4.25,VS2,J,Premium,1.005891,1.607059,0.625920,0.929487,0.006139
1,3513,1.02,61.6,58.0,6.40,6.35,3.93,VS2,J,Premium,1.007874,1.628499,0.618898,0.941558,0.006386

In [80]:
#Haciendo el modelo me da un error dónde algunos valores tienden a infinito por lo que elimino esa posibilidad

df_training.replace([np.inf, -np.inf], 0 , inplace=True)

In [81]:
#divido el dataset en 2: numérico y categórico

df_num = df_training[["price","carat","depth","table","x","y","z","xy","xz","table_depth","carat/dimensons"]]
df_cat =df_training[["clarity","color","cut"]]

In [82]:
#Aplico One Hot enconding en las columnas categóricas

df_cat = ["clarity","color","cut"]
df_one_hot_encoding = pd.get_dummies(df_training[df_cat], 
                                    columns=["clarity","color","cut"],
                                    dtype=float)
df_one_hot_encoding

,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2,color_D,color_E,color_F,color_G,color_H,color_I,color_J,cut_Fair,cut_Good,cut_Ideal,cut_Premium,cut_Very Good
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
40451,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
40452,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
40453,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
40454,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [83]:
diamonds_one_hot = pd.concat([df_num, df_one_hot_encoding], axis=1)
diamonds_one_hot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40455 entries, 0 to 40454
Data columns (total 31 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   price            40455 non-null  int64
 1   carat            40455 non-null  float64
 2   depth            40455 non-null  float64
 3   table            40455 non-null  float64
 4   x                40455 non-null  float64
 5   y                40455 non-null  float64
 6   z                40455 non-null  float64
 7   xy               40451 non-null  float64
 8   xz               40450 non-null  float64
 9   table_depth      40455 non-null  float64
 10  carat/dimensons  40455 non-null  float64
 11  clarity_I1       40455 non-null  float64
 12  clarity_IF       40455 non-null  float64
 13  clarity_SI1      40455 non-null  float64
 14  clarity_SI2      40455 non-null  float64
 15  clarity_VS1      40455 non-null  float64
 16  clarity_VS2      40455 non-null  float64
 17  clarity_VVS1     40455 non-null  float64
 18  clarity_VVS2     40455 non-null  float64
 19  color_D          40455 non-null  float64
 20  color_E          40455 non-null  float64
 21  color_F          40455 non-null  float64
 22  color_G          40455 non-null  float64
 23  color_H          40455 non-null  float64
 24  color_I          40455 non-null  float64
 25  color_J          40455 non-null  float64
 26  cut_Fair         40455 non-null  float64
 27  cut_Good         40455 non-null  float64
 28  cut_Ideal        40455 non-null  float64
 29  cut_Premium      40455 non-null  float64
 30  cut_Very Good    40455 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 9.6 MB

In [84]:
diamonds_one_hot['cut/weight_Fair']=diamonds_one_hot['cut_Fair']/diamonds_one_hot['carat']
diamonds_one_hot['cut/weight_Good']=diamonds_one_hot['cut_Good']/diamonds_one_hot['carat']
diamonds_one_hot['cut/weight_Ideal']=diamonds_one_hot['cut_Ideal']/diamonds_one_hot['carat']
diamonds_one_hot['cut/weight_Premium']=diamonds_one_hot['cut_Premium']/diamonds_one_hot['carat']
diamonds_one_hot['cut/weight_Very Good']=diamonds_one_hot['cut_Very Good']/diamonds_one_hot['carat']
diamonds_one_hot['color/weight_D']=diamonds_one_hot['color_D']/diamonds_one_hot['carat']
diamonds_one_hot['color/weight_E']=diamonds_one_hot['color_E']/diamonds_one_hot['carat']
diamonds_one_hot['color/weight_F']=diamonds_one_hot['color_F']/diamonds_one_hot['carat']
diamonds_one_hot['color/weight_G']=diamonds_one_hot['color_G']/diamonds_one_hot['carat']
diamonds_one_hot['color/weight_H']=diamonds_one_hot['color_H']/diamonds_one_hot['carat']
diamonds_one_hot['color/weight_I']=diamonds_one_hot['color_I']/diamonds_one_hot['carat']
diamonds_one_hot['color/weight_J']=diamonds_one_hot['color_J']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_I1']=diamonds_one_hot['clarity_I1']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_IF']=diamonds_one_hot['clarity_IF']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_SI1']=diamonds_one_hot['clarity_SI1']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_SI2']=diamonds_one_hot['clarity_SI2']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_VS1']=diamonds_one_hot['clarity_VS1']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_VS2']=diamonds_one_hot['clarity_VS2']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_VVS1']=diamonds_one_hot['clarity_VVS1']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_VVS2']=diamonds_one_hot['clarity_VVS2']/diamonds_one_hot['carat']
diamonds_one_hot

,price,carat,depth,table,x,y,z,xy,xz,table_depth,...,color/weight_I,color/weight_J,clarity/weight_I1,clarity/weight_IF,clarity/weight_SI1,clarity/weight_SI2,clarity/weight_VS1,clarity/weight_VS2,clarity/weight_VVS1,clarity/weight_VVS2
0,4268,1.21,62.4,58.0,6.83,6.79,4.25,1.005891,1.607059,0.929487,...,0.0,0.826446,0.000000,0.0,0.0,0.0,0.0,0.826446,0.0,0.0
1,3513,1.02,61.6,58.0,6.40,6.35,3.93,1.007874,1.628499,0.941558,...,0.0,0.980392,0.000000,0.0,0.0,0.0,0.0,0.980392,0.0,0.0
2,1792,0.77,62.3,58.0,5.86,5.80,3.63,1.010345,1.614325,0.930979,...,0.0,1.298701,0.000000,0.0,0.0,0.0,0.0,1.298701,0.0,0.0
3,7553,1.51,59.6,60.0,7.58,7.48,4.49,1.013369,1.688196,1.006711,...,0.0,0.662252,0.000000,0.0,0.0,0.0,0.0,0.662252,0.0,0.0
4,1176,0.57,60.2,62.0,5.40,5.33,3.23,1.013133,1.671827,1.029900,...,0.0,1.754386,0.000000,0.0,0.0,0.0,0.0,1.754386,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,1019,0.57,59.5,57.0,5.46,5.42,3.24,1.007380,1.685185,0.957983,...,0.0,0.000000,1.754386,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
40451,6096,1.44,63.2,55.0,7.21,7.18,4.54,1.004178,1.588106,0.870253,...,0.0,0.000000,0.694444,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
40452,3459,1.02,61.2,56.0,6.47,6.50,3.97,0.995385,1.629723,0.915033,...,0.0,0.000000,0.980392,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
40453,4428,1.28,61.6,57.0,6.93,6.96,4.28,0.995690,1.619159,0.925325,...,0.0,0.000000,0.781250,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
40454,6299,1.54,61.6,55.0,7.43,7.40,4.57,1.004054,1.625821,0.892857,...,0.0,0.000000,0.649351,0.0,0.0,0.0,0.0,0.000000,0.0,0.0

In [85]:
diamonds_one_hot = diamonds_one_hot.drop(columns=['clarity_I1',
'clarity_IF',
'clarity_SI1',
'clarity_SI2',
'clarity_VS1',
'clarity_VS2',
'clarity_VVS1',
'clarity_VVS2',
'color_D',
'color_E',
'color_F',
'color_G',
'color_H',
'color_I',
'color_J',
'cut_Fair',
'cut_Good',
'cut_Ideal',
'cut_Premium',
'cut_Very Good'], axis=1)

diamonds_one_hot

,price,carat,depth,table,x,y,z,xy,xz,table_depth,...,color/weight_I,color/weight_J,clarity/weight_I1,clarity/weight_IF,clarity/weight_SI1,clarity/weight_SI2,clarity/weight_VS1,clarity/weight_VS2,clarity/weight_VVS1,clarity/weight_VVS2
0,4268,1.21,62.4,58.0,6.83,6.79,4.25,1.005891,1.607059,0.929487,...,0.0,0.826446,0.000000,0.0,0.0,0.0,0.0,0.826446,0.0,0.0
1,3513,1.02,61.6,58.0,6.40,6.35,3.93,1.007874,1.628499,0.941558,...,0.0,0.980392,0.000000,0.0,0.0,0.0,0.0,0.980392,0.0,0.0
2,1792,0.77,62.3,58.0,5.86,5.80,3.63,1.010345,1.614325,0.930979,...,0.0,1.298701,0.000000,0.0,0.0,0.0,0.0,1.298701,0.0,0.0
3,7553,1.51,59.6,60.0,7.58,7.48,4.49,1.013369,1.688196,1.006711,...,0.0,0.662252,0.000000,0.0,0.0,0.0,0.0,0.662252,0.0,0.0
4,1176,0.57,60.2,62.0,5.40,5.33,3.23,1.013133,1.671827,1.029900,...,0.0,1.754386,0.000000,0.0,0.0,0.0,0.0,1.754386,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,1019,0.57,59.5,57.0,5.46,5.42,3.24,1.007380,1.685185,0.957983,...,0.0,0.000000,1.754386,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
40451,6096,1.44,63.2,55.0,7.21,7.18,4.54,1.004178,1.588106,0.870253,...,0.0,0.000000,0.694444,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
40452,3459,1.02,61.2,56.0,6.47,6.50,3.97,0.995385,1.629723,0.915033,...,0.0,0.000000,0.980392,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
40453,4428,1.28,61.6,57.0,6.93,6.96,4.28,0.995690,1.619159,0.925325,...,0.0,0.000000,0.781250,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
40454,6299,1.54,61.6,55.0,7.43,7.40,4.57,1.004054,1.625821,0.892857,...,0.0,0.000000,0.649351,0.0,0.0,0.0,0.0,0.000000,0.0,0.0

In [86]:
diamonds_one_hot['volume'] = diamonds_one_hot['x']*diamonds_one_hot['y']*diamonds_one_hot['z']
diamonds_one_hot

,price,carat,depth,table,x,y,z,xy,xz,table_depth,...,color/weight_J,clarity/weight_I1,clarity/weight_IF,clarity/weight_SI1,clarity/weight_SI2,clarity/weight_VS1,clarity/weight_VS2,clarity/weight_VVS1,clarity/weight_VVS2,volume
0,4268,1.21,62.4,58.0,6.83,6.79,4.25,1.005891,1.607059,0.929487,...,0.826446,0.000000,0.0,0.0,0.0,0.0,0.826446,0.0,0.0,197.096725
1,3513,1.02,61.6,58.0,6.40,6.35,3.93,1.007874,1.628499,0.941558,...,0.980392,0.000000,0.0,0.0,0.0,0.0,0.980392,0.0,0.0,159.715200
2,1792,0.77,62.3,58.0,5.86,5.80,3.63,1.010345,1.614325,0.930979,...,1.298701,0.000000,0.0,0.0,0.0,0.0,1.298701,0.0,0.0,123.376440
3,7553,1.51,59.6,60.0,7.58,7.48,4.49,1.013369,1.688196,1.006711,...,0.662252,0.000000,0.0,0.0,0.0,0.0,0.662252,0.0,0.0,254.575816
4,1176,0.57,60.2,62.0,5.40,5.33,3.23,1.013133,1.671827,1.029900,...,1.754386,0.000000,0.0,0.0,0.0,0.0,1.754386,0.0,0.0,92.965860
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,1019,0.57,59.5,57.0,5.46,5.42,3.24,1.007380,1.685185,0.957983,...,0.000000,1.754386,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,95.881968
40451,6096,1.44,63.2,55.0,7.21,7.18,4.54,1.004178,1.588106,0.870253,...,0.000000,0.694444,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,235.025812
40452,3459,1.02,61.2,56.0,6.47,6.50,3.97,0.995385,1.629723,0.915033,...,0.000000,0.980392,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,166.958350
40453,4428,1.28,61.6,57.0,6.93,6.96,4.28,0.995690,1.619159,0.925325,...,0.000000,0.781250,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,206.436384
40454,6299,1.54,61.6,55.0,7.43,7.40,4.57,1.004054,1.625821,0.892857,...,0.000000,0.649351,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,251.267740

In [87]:
#Aplico los mismos pasos sobre el dataset de test

df_test = pd.read_csv('./../data/diamonds_test.csv')
df_test

,id,carat,cut,color,clarity,depth,table,x,y,z,city
0,0,0.79,Very Good,F,SI1,62.7,60.0,5.82,5.89,3.67,Amsterdam
1,1,1.20,Ideal,J,VS1,61.0,57.0,6.81,6.89,4.18,Surat
2,2,1.57,Premium,H,SI1,62.2,61.0,7.38,7.32,4.57,Kimberly
3,3,0.90,Very Good,F,SI1,63.8,54.0,6.09,6.13,3.90,Kimberly
4,4,0.50,Very Good,F,VS1,62.9,58.0,5.05,5.09,3.19,Amsterdam
...,...,...,...,...,...,...,...,...,...,...,...
13480,13480,0.57,Ideal,E,SI1,61.9,56.0,5.35,5.32,3.30,Amsterdam
13481,13481,0.71,Ideal,I,VS2,62.2,55.0,5.71,5.73,3.56,New York City
13482,13482,0.70,Ideal,F,VS1,61.6,55.0,5.75,5.71,3.53,Tel Aviv
13483,13483,0.70,Very Good,F,SI2,58.8,57.0,5.85,5.89,3.45,Surat
13484,13484,0.40,Ideal,I,VVS2,62.4,55.0,4.70,4.73,2.94,New York City

In [88]:
#Elimino "city"

df_test = df_test.drop(columns='city')
df_test[:2]

   id  carat        cut color clarity  depth  table     x     y     z
0   0   0.79  Very Good     F     SI1   62.7   60.0  5.82  5.89  3.67
1   1   1.20      Ideal     J     VS1   61.0   57.0  6.81  6.89  4.18

In [89]:
#Preparo el dataset con nuevos features

df_test['xy'] = df_test['x']/df_test['y']
df_test['xz'] = df_test['x']/df_test['z']
df_test['zy'] = df_test['z']/df_test['y']
df_test['table_depth'] = df_test['table']/df_test['depth']
df_test['carat/dimensons'] = df_test ['carat'] / (df_test['x']* df_test['y'] * df_test['z'])
df_test[:2]

,id,carat,cut,color,clarity,depth,table,x,y,z,xy,xz,zy,table_depth,carat/dimensons
0,0,0.79,Very Good,F,SI1,62.7,60.0,5.82,5.89,3.67,0.988115,1.585831,0.623090,0.956938,0.006279
1,1,1.20,Ideal,J,VS1,61.0,57.0,6.81,6.89,4.18,0.988389,1.629187,0.606676,0.934426,0.006118

In [90]:
df_test.replace([np.inf, -np.inf], 0 , inplace=True)

In [91]:
#divido el dataset en 2: numérico y categórico

df_test_num = df_test[["carat","depth","table","x","y","z","xy","xz","table_depth","carat/dimensons"]]
df_test_cat = df_test[["clarity","color","cut"]]

In [92]:
#Aplico One Hot enconding en las columnas categóricas

df_test_cat = ["clarity","color","cut"]
diamonds_test_one_hot = pd.get_dummies(df_test[df_cat], 
                                    columns=["clarity","color","cut"],
                                    dtype=float)
diamonds_test_one_hot[:2]

,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2,color_D,color_E,color_F,color_G,color_H,color_I,color_J,cut_Fair,cut_Good,cut_Ideal,cut_Premium,cut_Very Good
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0

In [93]:
diamonds_test_one_hot = pd.concat([df_test_num, diamonds_test_one_hot], axis=1)
diamonds_test_one_hot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13485 entries, 0 to 13484
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   carat            13485 non-null  float64
 1   depth            13485 non-null  float64
 2   table            13485 non-null  float64
 3   x                13485 non-null  float64
 4   y                13485 non-null  float64
 5   z                13485 non-null  float64
 6   xy               13482 non-null  float64
 7   xz               13482 non-null  float64
 8   table_depth      13485 non-null  float64
 9   carat/dimensons  13485 non-null  float64
 10  clarity_I1       13485 non-null  float64
 11  clarity_IF       13485 non-null  float64
 12  clarity_SI1      13485 non-null  float64
 13  clarity_SI2      13485 non-null  float64
 14  clarity_VS1      13485 non-null  float64
 15  clarity_VS2      13485 non-null  float64
 16  clarity_VVS1     13485 non-null  float64
 17  clarity_VVS2     13485 non-null  float64
 18  color_D          13485 non-null  float64
 19  color_E          13485 non-null  float64
 20  color_F          13485 non-null  float64
 21  color_G          13485 non-null  float64
 22  color_H          13485 non-null  float64
 23  color_I          13485 non-null  float64
 24  color_J          13485 non-null  float64
 25  cut_Fair         13485 non-null  float64
 26  cut_Good         13485 non-null  float64
 27  cut_Ideal        13485 non-null  float64
 28  cut_Premium      13485 non-null  float64
 29  cut_Very Good    13485 non-null  float64
dtypes: float64(30)
memory usage: 3.1 MB

In [94]:
diamonds_test_one_hot['cut/weight_Fair']=diamonds_test_one_hot['cut_Fair']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['cut/weight_Good']=diamonds_test_one_hot['cut_Good']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['cut/weight_Ideal']=diamonds_test_one_hot['cut_Ideal']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['cut/weight_Premium']=diamonds_test_one_hot['cut_Premium']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['cut/weight_Very Good']=diamonds_test_one_hot['cut_Very Good']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['color/weight_D']=diamonds_test_one_hot['color_D']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['color/weight_E']=diamonds_test_one_hot['color_E']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['color/weight_F']=diamonds_test_one_hot['color_F']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['color/weight_G']=diamonds_test_one_hot['color_G']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['color/weight_H']=diamonds_test_one_hot['color_H']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['color/weight_I']=diamonds_test_one_hot['color_I']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['color/weight_J']=diamonds_test_one_hot['color_J']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_I1']=diamonds_test_one_hot['clarity_I1']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_IF']=diamonds_test_one_hot['clarity_IF']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_SI1']=diamonds_test_one_hot['clarity_SI1']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_SI2']=diamonds_test_one_hot['clarity_SI2']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_VS1']=diamonds_test_one_hot['clarity_VS1']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_VS2']=diamonds_test_one_hot['clarity_VS2']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_VVS1']=diamonds_test_one_hot['clarity_VVS1']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_VVS2']=diamonds_test_one_hot['clarity_VVS2']/diamonds_test_one_hot['carat']
diamonds_test_one_hot

,carat,depth,table,x,y,z,xy,xz,table_depth,carat/dimensons,...,color/weight_I,color/weight_J,clarity/weight_I1,clarity/weight_IF,clarity/weight_SI1,clarity/weight_SI2,clarity/weight_VS1,clarity/weight_VS2,clarity/weight_VVS1,clarity/weight_VVS2
0,0.79,62.7,60.0,5.82,5.89,3.67,0.988115,1.585831,0.956938,0.006279,...,0.000000,0.000000,0.0,0.0,1.265823,0.000000,0.000000,0.000000,0.0,0.0
1,1.20,61.0,57.0,6.81,6.89,4.18,0.988389,1.629187,0.934426,0.006118,...,0.000000,0.833333,0.0,0.0,0.000000,0.000000,0.833333,0.000000,0.0,0.0
2,1.57,62.2,61.0,7.38,7.32,4.57,1.008197,1.614880,0.980707,0.006359,...,0.000000,0.000000,0.0,0.0,0.636943,0.000000,0.000000,0.000000,0.0,0.0
3,0.90,63.8,54.0,6.09,6.13,3.90,0.993475,1.561538,0.846395,0.006182,...,0.000000,0.000000,0.0,0.0,1.111111,0.000000,0.000000,0.000000,0.0,0.0
4,0.50,62.9,58.0,5.05,5.09,3.19,0.992141,1.583072,0.922099,0.006098,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,2.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,0.57,61.9,56.0,5.35,5.32,3.30,1.005639,1.621212,0.904685,0.006069,...,0.000000,0.000000,0.0,0.0,1.754386,0.000000,0.000000,0.000000,0.0,0.0
13481,0.71,62.2,55.0,5.71,5.73,3.56,0.996510,1.603933,0.884244,0.006096,...,1.408451,0.000000,0.0,0.0,0.000000,0.000000,0.000000,1.408451,0.0,0.0
13482,0.70,61.6,55.0,5.75,5.71,3.53,1.007005,1.628895,0.892857,0.006040,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,1.428571,0.000000,0.0,0.0
13483,0.70,58.8,57.0,5.85,5.89,3.45,0.993209,1.695652,0.969388,0.005889,...,0.000000,0.000000,0.0,0.0,0.000000,1.428571,0.000000,0.000000,0.0,0.0
13484,0.40,62.4,55.0,4.70,4.73,2.94,0.993658,1.598639,0.881410,0.006120,...,2.500000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,2.5

In [95]:
diamonds_test_one_hot = diamonds_test_one_hot.drop(columns=['clarity_I1',
'clarity_IF',
'clarity_SI1',
'clarity_SI2',
'clarity_VS1',
'clarity_VS2',
'clarity_VVS1',
'clarity_VVS2',
'color_D',
'color_E',
'color_F',
'color_G',
'color_H',
'color_I',
'color_J',
'cut_Fair',
'cut_Good',
'cut_Ideal',
'cut_Premium',
'cut_Very Good'], axis=1)

diamonds_test_one_hot

,carat,depth,table,x,y,z,xy,xz,table_depth,carat/dimensons,...,color/weight_I,color/weight_J,clarity/weight_I1,clarity/weight_IF,clarity/weight_SI1,clarity/weight_SI2,clarity/weight_VS1,clarity/weight_VS2,clarity/weight_VVS1,clarity/weight_VVS2
0,0.79,62.7,60.0,5.82,5.89,3.67,0.988115,1.585831,0.956938,0.006279,...,0.000000,0.000000,0.0,0.0,1.265823,0.000000,0.000000,0.000000,0.0,0.0
1,1.20,61.0,57.0,6.81,6.89,4.18,0.988389,1.629187,0.934426,0.006118,...,0.000000,0.833333,0.0,0.0,0.000000,0.000000,0.833333,0.000000,0.0,0.0
2,1.57,62.2,61.0,7.38,7.32,4.57,1.008197,1.614880,0.980707,0.006359,...,0.000000,0.000000,0.0,0.0,0.636943,0.000000,0.000000,0.000000,0.0,0.0
3,0.90,63.8,54.0,6.09,6.13,3.90,0.993475,1.561538,0.846395,0.006182,...,0.000000,0.000000,0.0,0.0,1.111111,0.000000,0.000000,0.000000,0.0,0.0
4,0.50,62.9,58.0,5.05,5.09,3.19,0.992141,1.583072,0.922099,0.006098,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,2.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,0.57,61.9,56.0,5.35,5.32,3.30,1.005639,1.621212,0.904685,0.006069,...,0.000000,0.000000,0.0,0.0,1.754386,0.000000,0.000000,0.000000,0.0,0.0
13481,0.71,62.2,55.0,5.71,5.73,3.56,0.996510,1.603933,0.884244,0.006096,...,1.408451,0.000000,0.0,0.0,0.000000,0.000000,0.000000,1.408451,0.0,0.0
13482,0.70,61.6,55.0,5.75,5.71,3.53,1.007005,1.628895,0.892857,0.006040,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,1.428571,0.000000,0.0,0.0
13483,0.70,58.8,57.0,5.85,5.89,3.45,0.993209,1.695652,0.969388,0.005889,...,0.000000,0.000000,0.0,0.0,0.000000,1.428571,0.000000,0.000000,0.0,0.0
13484,0.40,62.4,55.0,4.70,4.73,2.94,0.993658,1.598639,0.881410,0.006120,...,2.500000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,2.5

In [96]:
diamonds_test_one_hot['volume'] = diamonds_test_one_hot['x']*diamonds_test_one_hot['y']*diamonds_test_one_hot['z']
diamonds_test_one_hot[:2]

,carat,depth,table,x,y,z,xy,xz,table_depth,carat/dimensons,...,color/weight_J,clarity/weight_I1,clarity/weight_IF,clarity/weight_SI1,clarity/weight_SI2,clarity/weight_VS1,clarity/weight_VS2,clarity/weight_VVS1,clarity/weight_VVS2,volume
0,0.79,62.7,60.0,5.82,5.89,3.67,0.988115,1.585831,0.956938,0.006279,...,0.000000,0.0,0.0,1.265823,0.0,0.000000,0.0,0.0,0.0,125.806866
1,1.20,61.0,57.0,6.81,6.89,4.18,0.988389,1.629187,0.934426,0.006118,...,0.833333,0.0,0.0,0.000000,0.0,0.833333,0.0,0.0,0.0,196.129362

In [97]:
#Tengo un error en el modelo dónde me apaerecen algunos valores nulos así que los sustityo por 0

diamonds_one_hot.isnull().sum()

price                   0
carat                   0
depth                   0
table                   0
x                       0
y                       0
z                       0
xy                      4
xz                      5
table_depth             0
carat/dimensons         0
cut/weight_Fair         0
cut/weight_Good         0
cut/weight_Ideal        0
cut/weight_Premium      0
cut/weight_Very Good    0
color/weight_D          0
color/weight_E          0
color/weight_F          0
color/weight_G          0
color/weight_H          0
color/weight_I          0
color/weight_J          0
clarity/weight_I1       0
clarity/weight_IF       0
clarity/weight_SI1      0
clarity/weight_SI2      0
clarity/weight_VS1      0
clarity/weight_VS2      0
clarity/weight_VVS1     0
clarity/weight_VVS2     0
volume                  0
dtype: int64

In [98]:
diamonds_one_hot.fillna(0, inplace=True)
diamonds_one_hot.isnull().sum()

price                   0
carat                   0
depth                   0
table                   0
x                       0
y                       0
z                       0
xy                      0
xz                      0
table_depth             0
carat/dimensons         0
cut/weight_Fair         0
cut/weight_Good         0
cut/weight_Ideal        0
cut/weight_Premium      0
cut/weight_Very Good    0
color/weight_D          0
color/weight_E          0
color/weight_F          0
color/weight_G          0
color/weight_H          0
color/weight_I          0
color/weight_J          0
clarity/weight_I1       0
clarity/weight_IF       0
clarity/weight_SI1      0
clarity/weight_SI2      0
clarity/weight_VS1      0
clarity/weight_VS2      0
clarity/weight_VVS1     0
clarity/weight_VVS2     0
volume                  0
dtype: int64

In [99]:
diamonds_test_one_hot.isnull().sum()

carat                   0
depth                   0
table                   0
x                       0
y                       0
z                       0
xy                      3
xz                      3
table_depth             0
carat/dimensons         0
cut/weight_Fair         0
cut/weight_Good         0
cut/weight_Ideal        0
cut/weight_Premium      0
cut/weight_Very Good    0
color/weight_D          0
color/weight_E          0
color/weight_F          0
color/weight_G          0
color/weight_H          0
color/weight_I          0
color/weight_J          0
clarity/weight_I1       0
clarity/weight_IF       0
clarity/weight_SI1      0
clarity/weight_SI2      0
clarity/weight_VS1      0
clarity/weight_VS2      0
clarity/weight_VVS1     0
clarity/weight_VVS2     0
volume                  0
dtype: int64

In [100]:
diamonds_test_one_hot.fillna(0, inplace=True)
diamonds_test_one_hot.isnull().sum()

carat                   0
depth                   0
table                   0
x                       0
y                       0
z                       0
xy                      0
xz                      0
table_depth             0
carat/dimensons         0
cut/weight_Fair         0
cut/weight_Good         0
cut/weight_Ideal        0
cut/weight_Premium      0
cut/weight_Very Good    0
color/weight_D          0
color/weight_E          0
color/weight_F          0
color/weight_G          0
color/weight_H          0
color/weight_I          0
color/weight_J          0
clarity/weight_I1       0
clarity/weight_IF       0
clarity/weight_SI1      0
clarity/weight_SI2      0
clarity/weight_VS1      0
clarity/weight_VS2      0
clarity/weight_VVS1     0
clarity/weight_VVS2     0
volume                  0
dtype: int64

In [101]:
export_train = diamonds_one_hot.to_csv('./../data/training_new_preprocesing.csv', index=False)

In [102]:
export_test = diamonds_test_one_hot.to_csv('./../data/test_new_procesing.csv', index=False)