In [1]:
#importo las librerias necesarias

import pandas as pd

In [2]:
#Trabajo sobre el dataset de training

df_final = pd.read_csv('./../data/diamons_clean.csv')
df_final.head()

   price  carat  depth  table     x     y     z   city clarity color      cut
0   4268   1.21   62.4   58.0  6.83  6.79  4.25  Dubai     VS2     J  Premium
1   3513   1.02   61.6   58.0  6.40  6.35  3.93  Dubai     VS2     J  Premium
2   1792   0.77   62.3   58.0  5.86  5.80  3.63  Dubai     VS2     J  Premium
3   7553   1.51   59.6   60.0  7.58  7.48  4.49  Dubai     VS2     J  Premium
4   1176   0.57   60.2   62.0  5.40  5.33  3.23  Dubai     VS2     J  Premium

In [3]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40455 entries, 0 to 40454
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   price    40455 non-null  int64
 1   carat    40455 non-null  float64
 2   depth    40455 non-null  float64
 3   table    40455 non-null  float64
 4   x        40455 non-null  float64
 5   y        40455 non-null  float64
 6   z        40455 non-null  float64
 7   city     40455 non-null  object
 8   clarity  40455 non-null  object
 9   color    40455 non-null  object
 10  cut      40455 non-null  object
dtypes: float64(6), int64(1), object(4)
memory usage: 3.4+ MB

In [4]:
#Elimino la columna city

df_final = df_final.drop(columns='city')
df_final[:2]

   price  carat  depth  table     x     y     z clarity color      cut
0   4268   1.21   62.4   58.0  6.83  6.79  4.25     VS2     J  Premium
1   3513   1.02   61.6   58.0  6.40  6.35  3.93     VS2     J  Premium

In [5]:
#Cargo el dataset de test

df_test = pd.read_csv('./../data/diamonds_test.csv')
df_test

,id,carat,cut,color,clarity,depth,table,x,y,z,city
0,0,0.79,Very Good,F,SI1,62.7,60.0,5.82,5.89,3.67,Amsterdam
1,1,1.20,Ideal,J,VS1,61.0,57.0,6.81,6.89,4.18,Surat
2,2,1.57,Premium,H,SI1,62.2,61.0,7.38,7.32,4.57,Kimberly
3,3,0.90,Very Good,F,SI1,63.8,54.0,6.09,6.13,3.90,Kimberly
4,4,0.50,Very Good,F,VS1,62.9,58.0,5.05,5.09,3.19,Amsterdam
...,...,...,...,...,...,...,...,...,...,...,...
13480,13480,0.57,Ideal,E,SI1,61.9,56.0,5.35,5.32,3.30,Amsterdam
13481,13481,0.71,Ideal,I,VS2,62.2,55.0,5.71,5.73,3.56,New York City
13482,13482,0.70,Ideal,F,VS1,61.6,55.0,5.75,5.71,3.53,Tel Aviv
13483,13483,0.70,Very Good,F,SI2,58.8,57.0,5.85,5.89,3.45,Surat
13484,13484,0.40,Ideal,I,VVS2,62.4,55.0,4.70,4.73,2.94,New York City

In [7]:
#le quito la columna city e id para que queden iguales
df_test = df_test.drop(columns='city')

In [8]:
df_test = df_test.drop(columns='id')
df_test

       carat        cut color clarity  depth  table     x     y     z
0       0.79  Very Good     F     SI1   62.7   60.0  5.82  5.89  3.67
1       1.20      Ideal     J     VS1   61.0   57.0  6.81  6.89  4.18
2       1.57    Premium     H     SI1   62.2   61.0  7.38  7.32  4.57
3       0.90  Very Good     F     SI1   63.8   54.0  6.09  6.13  3.90
4       0.50  Very Good     F     VS1   62.9   58.0  5.05  5.09  3.19
...      ...        ...   ...     ...    ...    ...   ...   ...   ...
13480   0.57      Ideal     E     SI1   61.9   56.0  5.35  5.32  3.30
13481   0.71      Ideal     I     VS2   62.2   55.0  5.71  5.73  3.56
13482   0.70      Ideal     F     VS1   61.6   55.0  5.75  5.71  3.53
13483   0.70  Very Good     F     SI2   58.8   57.0  5.85  5.89  3.45
13484   0.40      Ideal     I    VVS2   62.4   55.0  4.70  4.73  2.94

[13485 rows x 9 columns]

In [9]:
#Cargo el dataset de mi mejor modelo de entrenamiento para coger los precios

df_price = pd.read_csv('./../data/one_hot_robust_RF_no_cities_operations_3.csv')
df_price[:3]

   id    price
0   0  3072.29
1   1  5386.83
2   2  9603.06

In [ ]:
#Añado la columna price con el precio de mi mejor modelo

In [10]:
#Le incluyo la media de precio

df_test['price'] = df_price['price']
df_test

       carat        cut color clarity  depth  table     x     y     z    price
0       0.79  Very Good     F     SI1   62.7   60.0  5.82  5.89  3.67  3072.29
1       1.20      Ideal     J     VS1   61.0   57.0  6.81  6.89  4.18  5386.83
2       1.57    Premium     H     SI1   62.2   61.0  7.38  7.32  4.57  9603.06
3       0.90  Very Good     F     SI1   63.8   54.0  6.09  6.13  3.90  4231.37
4       0.50  Very Good     F     VS1   62.9   58.0  5.05  5.09  3.19  1727.85
...      ...        ...   ...     ...    ...    ...   ...   ...   ...      ...
13480   0.57      Ideal     E     SI1   61.9   56.0  5.35  5.32  3.30  1976.56
13481   0.71      Ideal     I     VS2   62.2   55.0  5.71  5.73  3.56  2331.41
13482   0.70      Ideal     F     VS1   61.6   55.0  5.75  5.71  3.53  2910.38
13483   0.70  Very Good     F     SI2   58.8   57.0  5.85  5.89  3.45  2113.32
13484   0.40      Ideal     I    VVS2   62.4   55.0  4.70  4.73  2.94   824.77

[13485 rows x 10 columns]

In [11]:
#Ordeno el dataframe

df_test = df_test[['price','carat','depth','table','x','y','z','clarity','color','cut']]
df_test

         price  carat  depth  table     x     y     z clarity color        cut
0      3072.29   0.79   62.7   60.0  5.82  5.89  3.67     SI1     F  Very Good
1      5386.83   1.20   61.0   57.0  6.81  6.89  4.18     VS1     J      Ideal
2      9603.06   1.57   62.2   61.0  7.38  7.32  4.57     SI1     H    Premium
3      4231.37   0.90   63.8   54.0  6.09  6.13  3.90     SI1     F  Very Good
4      1727.85   0.50   62.9   58.0  5.05  5.09  3.19     VS1     F  Very Good
...        ...    ...    ...    ...   ...   ...   ...     ...   ...        ...
13480  1976.56   0.57   61.9   56.0  5.35  5.32  3.30     SI1     E      Ideal
13481  2331.41   0.71   62.2   55.0  5.71  5.73  3.56     VS2     I      Ideal
13482  2910.38   0.70   61.6   55.0  5.75  5.71  3.53     VS1     F      Ideal
13483  2113.32   0.70   58.8   57.0  5.85  5.89  3.45     SI2     F  Very Good
13484   824.77   0.40   62.4   55.0  4.70  4.73  2.94    VVS2     I      Ideal

[13485 rows x 10 columns]

In [12]:
#Uno ambos dataframes

frames = [df_final, df_test]

In [13]:
#reviso el dataframe que esté todo correcto

df_final = pd.concat(frames)
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53940 entries, 0 to 13484
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   price    53940 non-null  float64
 1   carat    53940 non-null  float64
 2   depth    53940 non-null  float64
 3   table    53940 non-null  float64
 4   x        53940 non-null  float64
 5   y        53940 non-null  float64
 6   z        53940 non-null  float64
 7   clarity  53940 non-null  object
 8   color    53940 non-null  object
 9   cut      53940 non-null  object
dtypes: float64(7), object(3)
memory usage: 4.5+ MB

In [14]:
#divido el dataset en 2: numérico y categórico

df_num = df_final[["price","carat","depth","table","x","y","z"]]
df_cat =df_final[["clarity","color","cut"]]

In [15]:
#Aplico One Hot enconding en las columnas categóricas

df_cat = ["clarity","color","cut"]
df_one_hot_encoding = pd.get_dummies(df_final[df_cat], 
                                    columns=["clarity","color","cut"],
                                    dtype=float)
df_one_hot_encoding

,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2,color_D,color_E,color_F,color_G,color_H,color_I,color_J,cut_Fair,cut_Good,cut_Ideal,cut_Premium,cut_Very Good
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
13481,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
13482,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
13483,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
13484,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

In [16]:
diamonds_one_hot = pd.concat([df_num, df_one_hot_encoding], axis=1)
diamonds_one_hot.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53940 entries, 0 to 13484
Data columns (total 27 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          53940 non-null  float64
 1   carat          53940 non-null  float64
 2   depth          53940 non-null  float64
 3   table          53940 non-null  float64
 4   x              53940 non-null  float64
 5   y              53940 non-null  float64
 6   z              53940 non-null  float64
 7   clarity_I1     53940 non-null  float64
 8   clarity_IF     53940 non-null  float64
 9   clarity_SI1    53940 non-null  float64
 10  clarity_SI2    53940 non-null  float64
 11  clarity_VS1    53940 non-null  float64
 12  clarity_VS2    53940 non-null  float64
 13  clarity_VVS1   53940 non-null  float64
 14  clarity_VVS2   53940 non-null  float64
 15  color_D        53940 non-null  float64
 16  color_E        53940 non-null  float64
 17  color_F        53940 non-null  float64
 18  color_G        53940 non-null  float64
 19  color_H        53940 non-null  float64
 20  color_I        53940 non-null  float64
 21  color_J        53940 non-null  float64
 22  cut_Fair       53940 non-null  float64
 23  cut_Good       53940 non-null  float64
 24  cut_Ideal      53940 non-null  float64
 25  cut_Premium    53940 non-null  float64
 26  cut_Very Good  53940 non-null  float64
dtypes: float64(27)
memory usage: 11.5 MB

In [17]:
diamonds_one_hot['cut/weight_Fair']=diamonds_one_hot['cut_Fair']/diamonds_one_hot['carat']
diamonds_one_hot['cut/weight_Good']=diamonds_one_hot['cut_Good']/diamonds_one_hot['carat']
diamonds_one_hot['cut/weight_Ideal']=diamonds_one_hot['cut_Ideal']/diamonds_one_hot['carat']
diamonds_one_hot['cut/weight_Premium']=diamonds_one_hot['cut_Premium']/diamonds_one_hot['carat']
diamonds_one_hot['cut/weight_Very Good']=diamonds_one_hot['cut_Very Good']/diamonds_one_hot['carat']
diamonds_one_hot['color/weight_D']=diamonds_one_hot['color_D']/diamonds_one_hot['carat']
diamonds_one_hot['color/weight_E']=diamonds_one_hot['color_E']/diamonds_one_hot['carat']
diamonds_one_hot['color/weight_F']=diamonds_one_hot['color_F']/diamonds_one_hot['carat']
diamonds_one_hot['color/weight_G']=diamonds_one_hot['color_G']/diamonds_one_hot['carat']
diamonds_one_hot['color/weight_H']=diamonds_one_hot['color_H']/diamonds_one_hot['carat']
diamonds_one_hot['color/weight_I']=diamonds_one_hot['color_I']/diamonds_one_hot['carat']
diamonds_one_hot['color/weight_J']=diamonds_one_hot['color_J']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_I1']=diamonds_one_hot['clarity_I1']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_IF']=diamonds_one_hot['clarity_IF']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_SI1']=diamonds_one_hot['clarity_SI1']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_SI2']=diamonds_one_hot['clarity_SI2']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_VS1']=diamonds_one_hot['clarity_VS1']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_VS2']=diamonds_one_hot['clarity_VS2']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_VVS1']=diamonds_one_hot['clarity_VVS1']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_VVS2']=diamonds_one_hot['clarity_VVS2']/diamonds_one_hot['carat']
diamonds_one_hot

,price,carat,depth,table,x,y,z,clarity_I1,clarity_IF,clarity_SI1,...,color/weight_I,color/weight_J,clarity/weight_I1,clarity/weight_IF,clarity/weight_SI1,clarity/weight_SI2,clarity/weight_VS1,clarity/weight_VS2,clarity/weight_VVS1,clarity/weight_VVS2
0,4268.00,1.21,62.4,58.0,6.83,6.79,4.25,0.0,0.0,0.0,...,0.000000,0.826446,0.0,0.0,0.000000,0.000000,0.000000,0.826446,0.0,0.0
1,3513.00,1.02,61.6,58.0,6.40,6.35,3.93,0.0,0.0,0.0,...,0.000000,0.980392,0.0,0.0,0.000000,0.000000,0.000000,0.980392,0.0,0.0
2,1792.00,0.77,62.3,58.0,5.86,5.80,3.63,0.0,0.0,0.0,...,0.000000,1.298701,0.0,0.0,0.000000,0.000000,0.000000,1.298701,0.0,0.0
3,7553.00,1.51,59.6,60.0,7.58,7.48,4.49,0.0,0.0,0.0,...,0.000000,0.662252,0.0,0.0,0.000000,0.000000,0.000000,0.662252,0.0,0.0
4,1176.00,0.57,60.2,62.0,5.40,5.33,3.23,0.0,0.0,0.0,...,0.000000,1.754386,0.0,0.0,0.000000,0.000000,0.000000,1.754386,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,1976.56,0.57,61.9,56.0,5.35,5.32,3.30,0.0,0.0,1.0,...,0.000000,0.000000,0.0,0.0,1.754386,0.000000,0.000000,0.000000,0.0,0.0
13481,2331.41,0.71,62.2,55.0,5.71,5.73,3.56,0.0,0.0,0.0,...,1.408451,0.000000,0.0,0.0,0.000000,0.000000,0.000000,1.408451,0.0,0.0
13482,2910.38,0.70,61.6,55.0,5.75,5.71,3.53,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,1.428571,0.000000,0.0,0.0
13483,2113.32,0.70,58.8,57.0,5.85,5.89,3.45,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.000000,1.428571,0.000000,0.000000,0.0,0.0
13484,824.77,0.40,62.4,55.0,4.70,4.73,2.94,0.0,0.0,0.0,...,2.500000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,2.5

In [18]:
diamonds_one_hot = diamonds_one_hot.drop(columns=['clarity_I1',
'clarity_IF',
'clarity_SI1',
'clarity_SI2',
'clarity_VS1',
'clarity_VS2',
'clarity_VVS1',
'clarity_VVS2',
'color_D',
'color_E',
'color_F',
'color_G',
'color_H',
'color_I',
'color_J',
'cut_Fair',
'cut_Good',
'cut_Ideal',
'cut_Premium',
'cut_Very Good'], axis=1)

diamonds_one_hot

,price,carat,depth,table,x,y,z,cut/weight_Fair,cut/weight_Good,cut/weight_Ideal,...,color/weight_I,color/weight_J,clarity/weight_I1,clarity/weight_IF,clarity/weight_SI1,clarity/weight_SI2,clarity/weight_VS1,clarity/weight_VS2,clarity/weight_VVS1,clarity/weight_VVS2
0,4268.00,1.21,62.4,58.0,6.83,6.79,4.25,0.0,0.0,0.000000,...,0.000000,0.826446,0.0,0.0,0.000000,0.000000,0.000000,0.826446,0.0,0.0
1,3513.00,1.02,61.6,58.0,6.40,6.35,3.93,0.0,0.0,0.000000,...,0.000000,0.980392,0.0,0.0,0.000000,0.000000,0.000000,0.980392,0.0,0.0
2,1792.00,0.77,62.3,58.0,5.86,5.80,3.63,0.0,0.0,0.000000,...,0.000000,1.298701,0.0,0.0,0.000000,0.000000,0.000000,1.298701,0.0,0.0
3,7553.00,1.51,59.6,60.0,7.58,7.48,4.49,0.0,0.0,0.000000,...,0.000000,0.662252,0.0,0.0,0.000000,0.000000,0.000000,0.662252,0.0,0.0
4,1176.00,0.57,60.2,62.0,5.40,5.33,3.23,0.0,0.0,0.000000,...,0.000000,1.754386,0.0,0.0,0.000000,0.000000,0.000000,1.754386,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,1976.56,0.57,61.9,56.0,5.35,5.32,3.30,0.0,0.0,1.754386,...,0.000000,0.000000,0.0,0.0,1.754386,0.000000,0.000000,0.000000,0.0,0.0
13481,2331.41,0.71,62.2,55.0,5.71,5.73,3.56,0.0,0.0,1.408451,...,1.408451,0.000000,0.0,0.0,0.000000,0.000000,0.000000,1.408451,0.0,0.0
13482,2910.38,0.70,61.6,55.0,5.75,5.71,3.53,0.0,0.0,1.428571,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,1.428571,0.000000,0.0,0.0
13483,2113.32,0.70,58.8,57.0,5.85,5.89,3.45,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.000000,1.428571,0.000000,0.000000,0.0,0.0
13484,824.77,0.40,62.4,55.0,4.70,4.73,2.94,0.0,0.0,2.500000,...,2.500000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,2.5

In [19]:
# Features + target

X = diamonds_one_hot[['carat',
                    'depth',
                    'table',
                    'x',
                    'y',
                    'z',
                    'cut/weight_Fair',
                    'cut/weight_Good',
                    'cut/weight_Ideal',
                    'cut/weight_Premium',
                    'cut/weight_Very Good',
                    'color/weight_D',
                    'color/weight_E',
                    'color/weight_F',
                    'color/weight_G',
                    'color/weight_H',
                    'color/weight_I',
                    'color/weight_J',
                    'clarity/weight_I1',
                    'clarity/weight_IF',
                    'clarity/weight_SI1',
                    'clarity/weight_SI2',
                    'clarity/weight_VS1',
                    'clarity/weight_VS2',
                    'clarity/weight_VVS1',
                    'clarity/weight_VVS2']]
y = pd.get_dummies(diamonds_one_hot[['price']], drop_first=True)
print(X.shape,y.shape)

(53940, 26) (53940, 1)

In [20]:
#Trabajo sobre el dataset de test

diamond = pd.read_csv('./../data/diamonds_test.csv')
diamond

,id,carat,cut,color,clarity,depth,table,x,y,z,city
0,0,0.79,Very Good,F,SI1,62.7,60.0,5.82,5.89,3.67,Amsterdam
1,1,1.20,Ideal,J,VS1,61.0,57.0,6.81,6.89,4.18,Surat
2,2,1.57,Premium,H,SI1,62.2,61.0,7.38,7.32,4.57,Kimberly
3,3,0.90,Very Good,F,SI1,63.8,54.0,6.09,6.13,3.90,Kimberly
4,4,0.50,Very Good,F,VS1,62.9,58.0,5.05,5.09,3.19,Amsterdam
...,...,...,...,...,...,...,...,...,...,...,...
13480,13480,0.57,Ideal,E,SI1,61.9,56.0,5.35,5.32,3.30,Amsterdam
13481,13481,0.71,Ideal,I,VS2,62.2,55.0,5.71,5.73,3.56,New York City
13482,13482,0.70,Ideal,F,VS1,61.6,55.0,5.75,5.71,3.53,Tel Aviv
13483,13483,0.70,Very Good,F,SI2,58.8,57.0,5.85,5.89,3.45,Surat
13484,13484,0.40,Ideal,I,VVS2,62.4,55.0,4.70,4.73,2.94,New York City

In [21]:
#Separo el dataset de test en categórico y numérico

diamond_test_num = diamond[["carat","depth","table","x","y","z"]]
diamond_test_cat = diamond[["clarity","color","cut"]]

In [22]:
#Aplico One Hot enconding en las columnas categóricas

diamond_test_cat = ["clarity","color","cut"]
diamonds_test_one_hot_encoding = pd.get_dummies(diamond[diamond_test_cat], 
                                    columns=["clarity","color","cut"],
                                    dtype=float)
diamonds_test_one_hot_encoding

,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2,color_D,color_E,color_F,color_G,color_H,color_I,color_J,cut_Fair,cut_Good,cut_Ideal,cut_Premium,cut_Very Good
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
13481,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
13482,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
13483,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
13484,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

In [23]:
diamonds_test_one_hot = pd.concat([diamond_test_num, diamonds_test_one_hot_encoding], axis=1)
diamonds_test_one_hot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13485 entries, 0 to 13484
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   carat          13485 non-null  float64
 1   depth          13485 non-null  float64
 2   table          13485 non-null  float64
 3   x              13485 non-null  float64
 4   y              13485 non-null  float64
 5   z              13485 non-null  float64
 6   clarity_I1     13485 non-null  float64
 7   clarity_IF     13485 non-null  float64
 8   clarity_SI1    13485 non-null  float64
 9   clarity_SI2    13485 non-null  float64
 10  clarity_VS1    13485 non-null  float64
 11  clarity_VS2    13485 non-null  float64
 12  clarity_VVS1   13485 non-null  float64
 13  clarity_VVS2   13485 non-null  float64
 14  color_D        13485 non-null  float64
 15  color_E        13485 non-null  float64
 16  color_F        13485 non-null  float64
 17  color_G        13485 non-null  float64
 18  color_H        13485 non-null  float64
 19  color_I        13485 non-null  float64
 20  color_J        13485 non-null  float64
 21  cut_Fair       13485 non-null  float64
 22  cut_Good       13485 non-null  float64
 23  cut_Ideal      13485 non-null  float64
 24  cut_Premium    13485 non-null  float64
 25  cut_Very Good  13485 non-null  float64
dtypes: float64(26)
memory usage: 2.7 MB

In [24]:
diamonds_test_one_hot['cut/weight_Fair']=diamonds_test_one_hot['cut_Fair']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['cut/weight_Good']=diamonds_test_one_hot['cut_Good']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['cut/weight_Ideal']=diamonds_test_one_hot['cut_Ideal']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['cut/weight_Premium']=diamonds_test_one_hot['cut_Premium']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['cut/weight_Very Good']=diamonds_test_one_hot['cut_Very Good']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['color/weight_D']=diamonds_test_one_hot['color_D']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['color/weight_E']=diamonds_test_one_hot['color_E']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['color/weight_F']=diamonds_test_one_hot['color_F']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['color/weight_G']=diamonds_test_one_hot['color_G']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['color/weight_H']=diamonds_test_one_hot['color_H']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['color/weight_I']=diamonds_test_one_hot['color_I']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['color/weight_J']=diamonds_test_one_hot['color_J']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_I1']=diamonds_test_one_hot['clarity_I1']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_IF']=diamonds_test_one_hot['clarity_IF']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_SI1']=diamonds_test_one_hot['clarity_SI1']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_SI2']=diamonds_test_one_hot['clarity_SI2']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_VS1']=diamonds_test_one_hot['clarity_VS1']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_VS2']=diamonds_test_one_hot['clarity_VS2']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_VVS1']=diamonds_test_one_hot['clarity_VVS1']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_VVS2']=diamonds_test_one_hot['clarity_VVS2']/diamonds_test_one_hot['carat']
diamonds_test_one_hot

,carat,depth,table,x,y,z,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,...,color/weight_I,color/weight_J,clarity/weight_I1,clarity/weight_IF,clarity/weight_SI1,clarity/weight_SI2,clarity/weight_VS1,clarity/weight_VS2,clarity/weight_VVS1,clarity/weight_VVS2
0,0.79,62.7,60.0,5.82,5.89,3.67,0.0,0.0,1.0,0.0,...,0.000000,0.000000,0.0,0.0,1.265823,0.000000,0.000000,0.000000,0.0,0.0
1,1.20,61.0,57.0,6.81,6.89,4.18,0.0,0.0,0.0,0.0,...,0.000000,0.833333,0.0,0.0,0.000000,0.000000,0.833333,0.000000,0.0,0.0
2,1.57,62.2,61.0,7.38,7.32,4.57,0.0,0.0,1.0,0.0,...,0.000000,0.000000,0.0,0.0,0.636943,0.000000,0.000000,0.000000,0.0,0.0
3,0.90,63.8,54.0,6.09,6.13,3.90,0.0,0.0,1.0,0.0,...,0.000000,0.000000,0.0,0.0,1.111111,0.000000,0.000000,0.000000,0.0,0.0
4,0.50,62.9,58.0,5.05,5.09,3.19,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,2.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,0.57,61.9,56.0,5.35,5.32,3.30,0.0,0.0,1.0,0.0,...,0.000000,0.000000,0.0,0.0,1.754386,0.000000,0.000000,0.000000,0.0,0.0
13481,0.71,62.2,55.0,5.71,5.73,3.56,0.0,0.0,0.0,0.0,...,1.408451,0.000000,0.0,0.0,0.000000,0.000000,0.000000,1.408451,0.0,0.0
13482,0.70,61.6,55.0,5.75,5.71,3.53,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,1.428571,0.000000,0.0,0.0
13483,0.70,58.8,57.0,5.85,5.89,3.45,0.0,0.0,0.0,1.0,...,0.000000,0.000000,0.0,0.0,0.000000,1.428571,0.000000,0.000000,0.0,0.0
13484,0.40,62.4,55.0,4.70,4.73,2.94,0.0,0.0,0.0,0.0,...,2.500000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,2.5

In [25]:
diamonds_test_one_hot = diamonds_test_one_hot.drop(columns=['clarity_I1',
'clarity_IF',
'clarity_SI1',
'clarity_SI2',
'clarity_VS1',
'clarity_VS2',
'clarity_VVS1',
'clarity_VVS2',
'color_D',
'color_E',
'color_F',
'color_G',
'color_H',
'color_I',
'color_J',
'cut_Fair',
'cut_Good',
'cut_Ideal',
'cut_Premium',
'cut_Very Good'], axis=1)

diamonds_test_one_hot

,carat,depth,table,x,y,z,cut/weight_Fair,cut/weight_Good,cut/weight_Ideal,cut/weight_Premium,...,color/weight_I,color/weight_J,clarity/weight_I1,clarity/weight_IF,clarity/weight_SI1,clarity/weight_SI2,clarity/weight_VS1,clarity/weight_VS2,clarity/weight_VVS1,clarity/weight_VVS2
0,0.79,62.7,60.0,5.82,5.89,3.67,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.0,1.265823,0.000000,0.000000,0.000000,0.0,0.0
1,1.20,61.0,57.0,6.81,6.89,4.18,0.0,0.0,0.833333,0.000000,...,0.000000,0.833333,0.0,0.0,0.000000,0.000000,0.833333,0.000000,0.0,0.0
2,1.57,62.2,61.0,7.38,7.32,4.57,0.0,0.0,0.000000,0.636943,...,0.000000,0.000000,0.0,0.0,0.636943,0.000000,0.000000,0.000000,0.0,0.0
3,0.90,63.8,54.0,6.09,6.13,3.90,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.0,1.111111,0.000000,0.000000,0.000000,0.0,0.0
4,0.50,62.9,58.0,5.05,5.09,3.19,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,2.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,0.57,61.9,56.0,5.35,5.32,3.30,0.0,0.0,1.754386,0.000000,...,0.000000,0.000000,0.0,0.0,1.754386,0.000000,0.000000,0.000000,0.0,0.0
13481,0.71,62.2,55.0,5.71,5.73,3.56,0.0,0.0,1.408451,0.000000,...,1.408451,0.000000,0.0,0.0,0.000000,0.000000,0.000000,1.408451,0.0,0.0
13482,0.70,61.6,55.0,5.75,5.71,3.53,0.0,0.0,1.428571,0.000000,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,1.428571,0.000000,0.0,0.0
13483,0.70,58.8,57.0,5.85,5.89,3.45,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.000000,1.428571,0.000000,0.000000,0.0,0.0
13484,0.40,62.4,55.0,4.70,4.73,2.94,0.0,0.0,2.500000,0.000000,...,2.500000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,2.5

In [26]:
export_train = diamonds_one_hot.to_csv('./../data/training_one_hot_no_cities_operations_result_data.csv', index=False)

In [27]:
export_test = diamonds_test_one_hot.to_csv('./../data/diamonds_test_one_hot_no_cities_operations_result_data.csv', index=False)