In [7]:
#importo las librerias necesarias

import pandas as pd

In [8]:
#Trabajo sobre el dataset de training

df_final = pd.read_csv('./../data/diamons_clean.csv')
df_final.head()

   price  carat  depth  table     x     y     z   city clarity color      cut
0   4268   1.21   62.4   58.0  6.83  6.79  4.25  Dubai     VS2     J  Premium
1   3513   1.02   61.6   58.0  6.40  6.35  3.93  Dubai     VS2     J  Premium
2   1792   0.77   62.3   58.0  5.86  5.80  3.63  Dubai     VS2     J  Premium
3   7553   1.51   59.6   60.0  7.58  7.48  4.49  Dubai     VS2     J  Premium
4   1176   0.57   60.2   62.0  5.40  5.33  3.23  Dubai     VS2     J  Premium

In [9]:
#reviso el dataframe que esté todo correcto

df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40455 entries, 0 to 40454
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   price    40455 non-null  int64
 1   carat    40455 non-null  float64
 2   depth    40455 non-null  float64
 3   table    40455 non-null  float64
 4   x        40455 non-null  float64
 5   y        40455 non-null  float64
 6   z        40455 non-null  float64
 7   city     40455 non-null  object
 8   clarity  40455 non-null  object
 9   color    40455 non-null  object
 10  cut      40455 non-null  object
dtypes: float64(6), int64(1), object(4)
memory usage: 3.4+ MB

In [10]:
#divido el dataset en 2: numérico y categórico

df_num = df_final[["price","carat","depth","table","x","y","z"]]
df_cat =df_final[["clarity","color","cut"]]

In [11]:
#Aplico One Hot enconding en las columnas categóricas

df_cat = ["clarity","color"]
df_one_hot_encoding = pd.get_dummies(df_final[df_cat], 
                                    columns=["clarity","color"],
                                    dtype=float)
df_one_hot_encoding

,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2,color_D,color_E,color_F,color_G,color_H,color_I,color_J
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
40451,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
40452,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
40453,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
40454,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [13]:
diamonds_one_hot = pd.concat([df_num, df_one_hot_encoding,df_final['cut']], axis=1)
diamonds_one_hot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40455 entries, 0 to 40454
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         40455 non-null  int64
 1   carat         40455 non-null  float64
 2   depth         40455 non-null  float64
 3   table         40455 non-null  float64
 4   x             40455 non-null  float64
 5   y             40455 non-null  float64
 6   z             40455 non-null  float64
 7   clarity_I1    40455 non-null  float64
 8   clarity_IF    40455 non-null  float64
 9   clarity_SI1   40455 non-null  float64
 10  clarity_SI2   40455 non-null  float64
 11  clarity_VS1   40455 non-null  float64
 12  clarity_VS2   40455 non-null  float64
 13  clarity_VVS1  40455 non-null  float64
 14  clarity_VVS2  40455 non-null  float64
 15  color_D       40455 non-null  float64
 16  color_E       40455 non-null  float64
 17  color_F       40455 non-null  float64
 18  color_G       40455 non-null  float64
 19  color_H       40455 non-null  float64
 20  color_I       40455 non-null  float64
 21  color_J       40455 non-null  float64
 22  cut           40455 non-null  object
dtypes: float64(21), int64(1), object(1)
memory usage: 7.1+ MB

In [14]:
diamonds_one_hot['cut'].unique()

array(['Premium', 'Fair', 'Very Good', 'Good', 'Ideal'], dtype=object)

In [17]:
cut_col  = {'Premium':5, 'Fair':4, 'Very Good':3, 'Good':2, 'Ideal':1}
def ordinal_encoding(x):
    for key in cut_col:
        if x == key:
            return cut_col[key]

In [18]:
diamonds_one_hot['cut'] = diamonds_one_hot['cut'].apply(ordinal_encoding)
diamonds_one_hot

,price,carat,depth,table,x,y,z,clarity_I1,clarity_IF,clarity_SI1,...,clarity_VVS1,clarity_VVS2,color_D,color_E,color_F,color_G,color_H,color_I,color_J,cut
0,4268,1.21,62.4,58.0,6.83,6.79,4.25,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,5
1,3513,1.02,61.6,58.0,6.40,6.35,3.93,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,5
2,1792,0.77,62.3,58.0,5.86,5.80,3.63,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,5
3,7553,1.51,59.6,60.0,7.58,7.48,4.49,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,5
4,1176,0.57,60.2,62.0,5.40,5.33,3.23,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,1019,0.57,59.5,57.0,5.46,5.42,3.24,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1
40451,6096,1.44,63.2,55.0,7.21,7.18,4.54,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1
40452,3459,1.02,61.2,56.0,6.47,6.50,3.97,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1
40453,4428,1.28,61.6,57.0,6.93,6.96,4.28,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1
40454,6299,1.54,61.6,55.0,7.43,7.40,4.57,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1

In [19]:
diamonds_one_hot['color/weight_D']=diamonds_one_hot['color_D']/diamonds_one_hot['carat']
diamonds_one_hot['color/weight_E']=diamonds_one_hot['color_E']/diamonds_one_hot['carat']
diamonds_one_hot['color/weight_F']=diamonds_one_hot['color_F']/diamonds_one_hot['carat']
diamonds_one_hot['color/weight_G']=diamonds_one_hot['color_G']/diamonds_one_hot['carat']
diamonds_one_hot['color/weight_H']=diamonds_one_hot['color_H']/diamonds_one_hot['carat']
diamonds_one_hot['color/weight_I']=diamonds_one_hot['color_I']/diamonds_one_hot['carat']
diamonds_one_hot['color/weight_J']=diamonds_one_hot['color_J']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_I1']=diamonds_one_hot['clarity_I1']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_IF']=diamonds_one_hot['clarity_IF']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_SI1']=diamonds_one_hot['clarity_SI1']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_SI2']=diamonds_one_hot['clarity_SI2']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_VS1']=diamonds_one_hot['clarity_VS1']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_VS2']=diamonds_one_hot['clarity_VS2']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_VVS1']=diamonds_one_hot['clarity_VVS1']/diamonds_one_hot['carat']
diamonds_one_hot['clarity/weight_VVS2']=diamonds_one_hot['clarity_VVS2']/diamonds_one_hot['carat']
diamonds_one_hot

,price,carat,depth,table,x,y,z,clarity_I1,clarity_IF,clarity_SI1,...,color/weight_I,color/weight_J,clarity/weight_I1,clarity/weight_IF,clarity/weight_SI1,clarity/weight_SI2,clarity/weight_VS1,clarity/weight_VS2,clarity/weight_VVS1,clarity/weight_VVS2
0,4268,1.21,62.4,58.0,6.83,6.79,4.25,0.0,0.0,0.0,...,0.0,0.826446,0.000000,0.0,0.0,0.0,0.0,0.826446,0.0,0.0
1,3513,1.02,61.6,58.0,6.40,6.35,3.93,0.0,0.0,0.0,...,0.0,0.980392,0.000000,0.0,0.0,0.0,0.0,0.980392,0.0,0.0
2,1792,0.77,62.3,58.0,5.86,5.80,3.63,0.0,0.0,0.0,...,0.0,1.298701,0.000000,0.0,0.0,0.0,0.0,1.298701,0.0,0.0
3,7553,1.51,59.6,60.0,7.58,7.48,4.49,0.0,0.0,0.0,...,0.0,0.662252,0.000000,0.0,0.0,0.0,0.0,0.662252,0.0,0.0
4,1176,0.57,60.2,62.0,5.40,5.33,3.23,0.0,0.0,0.0,...,0.0,1.754386,0.000000,0.0,0.0,0.0,0.0,1.754386,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,1019,0.57,59.5,57.0,5.46,5.42,3.24,1.0,0.0,0.0,...,0.0,0.000000,1.754386,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
40451,6096,1.44,63.2,55.0,7.21,7.18,4.54,1.0,0.0,0.0,...,0.0,0.000000,0.694444,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
40452,3459,1.02,61.2,56.0,6.47,6.50,3.97,1.0,0.0,0.0,...,0.0,0.000000,0.980392,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
40453,4428,1.28,61.6,57.0,6.93,6.96,4.28,1.0,0.0,0.0,...,0.0,0.000000,0.781250,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
40454,6299,1.54,61.6,55.0,7.43,7.40,4.57,1.0,0.0,0.0,...,0.0,0.000000,0.649351,0.0,0.0,0.0,0.0,0.000000,0.0,0.0

In [20]:
diamonds_one_hot = diamonds_one_hot.drop(columns=['clarity_I1',
'clarity_IF',
'clarity_SI1',
'clarity_SI2',
'clarity_VS1',
'clarity_VS2',
'clarity_VVS1',
'clarity_VVS2',
'color_D',
'color_E',
'color_F',
'color_G',
'color_H',
'color_I',
'color_J'], axis=1)

diamonds_one_hot

,price,carat,depth,table,x,y,z,cut,color/weight_D,color/weight_E,...,color/weight_I,color/weight_J,clarity/weight_I1,clarity/weight_IF,clarity/weight_SI1,clarity/weight_SI2,clarity/weight_VS1,clarity/weight_VS2,clarity/weight_VVS1,clarity/weight_VVS2
0,4268,1.21,62.4,58.0,6.83,6.79,4.25,5,0.0,0.0,...,0.0,0.826446,0.000000,0.0,0.0,0.0,0.0,0.826446,0.0,0.0
1,3513,1.02,61.6,58.0,6.40,6.35,3.93,5,0.0,0.0,...,0.0,0.980392,0.000000,0.0,0.0,0.0,0.0,0.980392,0.0,0.0
2,1792,0.77,62.3,58.0,5.86,5.80,3.63,5,0.0,0.0,...,0.0,1.298701,0.000000,0.0,0.0,0.0,0.0,1.298701,0.0,0.0
3,7553,1.51,59.6,60.0,7.58,7.48,4.49,5,0.0,0.0,...,0.0,0.662252,0.000000,0.0,0.0,0.0,0.0,0.662252,0.0,0.0
4,1176,0.57,60.2,62.0,5.40,5.33,3.23,5,0.0,0.0,...,0.0,1.754386,0.000000,0.0,0.0,0.0,0.0,1.754386,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,1019,0.57,59.5,57.0,5.46,5.42,3.24,1,0.0,0.0,...,0.0,0.000000,1.754386,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
40451,6096,1.44,63.2,55.0,7.21,7.18,4.54,1,0.0,0.0,...,0.0,0.000000,0.694444,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
40452,3459,1.02,61.2,56.0,6.47,6.50,3.97,1,0.0,0.0,...,0.0,0.000000,0.980392,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
40453,4428,1.28,61.6,57.0,6.93,6.96,4.28,1,0.0,0.0,...,0.0,0.000000,0.781250,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
40454,6299,1.54,61.6,55.0,7.43,7.40,4.57,1,0.0,0.0,...,0.0,0.000000,0.649351,0.0,0.0,0.0,0.0,0.000000,0.0,0.0

In [21]:
diamonds_one_hot['volume'] = diamonds_one_hot['x']*diamonds_one_hot['y']*diamonds_one_hot['z']
diamonds_one_hot

,price,carat,depth,table,x,y,z,cut,color/weight_D,color/weight_E,...,color/weight_J,clarity/weight_I1,clarity/weight_IF,clarity/weight_SI1,clarity/weight_SI2,clarity/weight_VS1,clarity/weight_VS2,clarity/weight_VVS1,clarity/weight_VVS2,volume
0,4268,1.21,62.4,58.0,6.83,6.79,4.25,5,0.0,0.0,...,0.826446,0.000000,0.0,0.0,0.0,0.0,0.826446,0.0,0.0,197.096725
1,3513,1.02,61.6,58.0,6.40,6.35,3.93,5,0.0,0.0,...,0.980392,0.000000,0.0,0.0,0.0,0.0,0.980392,0.0,0.0,159.715200
2,1792,0.77,62.3,58.0,5.86,5.80,3.63,5,0.0,0.0,...,1.298701,0.000000,0.0,0.0,0.0,0.0,1.298701,0.0,0.0,123.376440
3,7553,1.51,59.6,60.0,7.58,7.48,4.49,5,0.0,0.0,...,0.662252,0.000000,0.0,0.0,0.0,0.0,0.662252,0.0,0.0,254.575816
4,1176,0.57,60.2,62.0,5.40,5.33,3.23,5,0.0,0.0,...,1.754386,0.000000,0.0,0.0,0.0,0.0,1.754386,0.0,0.0,92.965860
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,1019,0.57,59.5,57.0,5.46,5.42,3.24,1,0.0,0.0,...,0.000000,1.754386,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,95.881968
40451,6096,1.44,63.2,55.0,7.21,7.18,4.54,1,0.0,0.0,...,0.000000,0.694444,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,235.025812
40452,3459,1.02,61.2,56.0,6.47,6.50,3.97,1,0.0,0.0,...,0.000000,0.980392,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,166.958350
40453,4428,1.28,61.6,57.0,6.93,6.96,4.28,1,0.0,0.0,...,0.000000,0.781250,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,206.436384
40454,6299,1.54,61.6,55.0,7.43,7.40,4.57,1,0.0,0.0,...,0.000000,0.649351,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,251.267740

In [23]:
# Features + target

X = diamonds_one_hot[['carat',
                    'depth',
                    'table',
                    'x',
                    'y',
                    'z',
                    'color/weight_D',
                    'color/weight_E',
                    'color/weight_F',
                    'color/weight_G',
                    'color/weight_H',
                    'color/weight_I',
                    'color/weight_J',
                    'clarity/weight_I1',
                    'clarity/weight_IF',
                    'clarity/weight_SI1',
                    'clarity/weight_SI2',
                    'clarity/weight_VS1',
                    'clarity/weight_VS2',
                    'clarity/weight_VVS1',
                    'clarity/weight_VVS2',
                     'cut',
                     'volume']]
y = pd.get_dummies(diamonds_one_hot[['price']], drop_first=True)
print(X.shape,y.shape)

(40455, 23) (40455, 1)

In [24]:
#Trabajo sobre el dataset de test

diamond = pd.read_csv('./../data/diamonds_test.csv')
diamond

,id,carat,cut,color,clarity,depth,table,x,y,z,city
0,0,0.79,Very Good,F,SI1,62.7,60.0,5.82,5.89,3.67,Amsterdam
1,1,1.20,Ideal,J,VS1,61.0,57.0,6.81,6.89,4.18,Surat
2,2,1.57,Premium,H,SI1,62.2,61.0,7.38,7.32,4.57,Kimberly
3,3,0.90,Very Good,F,SI1,63.8,54.0,6.09,6.13,3.90,Kimberly
4,4,0.50,Very Good,F,VS1,62.9,58.0,5.05,5.09,3.19,Amsterdam
...,...,...,...,...,...,...,...,...,...,...,...
13480,13480,0.57,Ideal,E,SI1,61.9,56.0,5.35,5.32,3.30,Amsterdam
13481,13481,0.71,Ideal,I,VS2,62.2,55.0,5.71,5.73,3.56,New York City
13482,13482,0.70,Ideal,F,VS1,61.6,55.0,5.75,5.71,3.53,Tel Aviv
13483,13483,0.70,Very Good,F,SI2,58.8,57.0,5.85,5.89,3.45,Surat
13484,13484,0.40,Ideal,I,VVS2,62.4,55.0,4.70,4.73,2.94,New York City

In [25]:
#Separo el dataset de test en categórico y numérico

diamond_test_num = diamond[["carat","depth","table","x","y","z"]]
diamond_test_cat = diamond[["clarity","color","cut"]]

In [26]:
#Aplico One Hot enconding en las columnas categóricas

diamond_test_cat = ["clarity","color"]
diamonds_test_one_hot_encoding = pd.get_dummies(diamond[diamond_test_cat], 
                                    columns=["clarity","color"],
                                    dtype=float)
diamonds_test_one_hot_encoding

,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2,color_D,color_E,color_F,color_G,color_H,color_I,color_J
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
13481,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13482,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
13483,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
13484,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [28]:
diamonds_test_one_hot = pd.concat([diamond_test_num, diamonds_test_one_hot_encoding,diamond['cut']], axis=1)
diamonds_test_one_hot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13485 entries, 0 to 13484
Data columns (total 22 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   carat         13485 non-null  float64
 1   depth         13485 non-null  float64
 2   table         13485 non-null  float64
 3   x             13485 non-null  float64
 4   y             13485 non-null  float64
 5   z             13485 non-null  float64
 6   clarity_I1    13485 non-null  float64
 7   clarity_IF    13485 non-null  float64
 8   clarity_SI1   13485 non-null  float64
 9   clarity_SI2   13485 non-null  float64
 10  clarity_VS1   13485 non-null  float64
 11  clarity_VS2   13485 non-null  float64
 12  clarity_VVS1  13485 non-null  float64
 13  clarity_VVS2  13485 non-null  float64
 14  color_D       13485 non-null  float64
 15  color_E       13485 non-null  float64
 16  color_F       13485 non-null  float64
 17  color_G       13485 non-null  float64
 18  color_H       13485 non-null  float64
 19  color_I       13485 non-null  float64
 20  color_J       13485 non-null  float64
 21  cut           13485 non-null  object
dtypes: float64(21), object(1)
memory usage: 2.3+ MB

In [29]:
diamonds_test_one_hot['cut'] = diamonds_test_one_hot['cut'].apply(ordinal_encoding)
diamonds_test_one_hot

,carat,depth,table,x,y,z,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,...,clarity_VVS1,clarity_VVS2,color_D,color_E,color_F,color_G,color_H,color_I,color_J,cut
0,0.79,62.7,60.0,5.82,5.89,3.67,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3
1,1.20,61.0,57.0,6.81,6.89,4.18,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
2,1.57,62.2,61.0,7.38,7.32,4.57,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,5
3,0.90,63.8,54.0,6.09,6.13,3.90,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3
4,0.50,62.9,58.0,5.05,5.09,3.19,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,0.57,61.9,56.0,5.35,5.32,3.30,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1
13481,0.71,62.2,55.0,5.71,5.73,3.56,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1
13482,0.70,61.6,55.0,5.75,5.71,3.53,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1
13483,0.70,58.8,57.0,5.85,5.89,3.45,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3
13484,0.40,62.4,55.0,4.70,4.73,2.94,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1

In [30]:
diamonds_test_one_hot['color/weight_D']=diamonds_test_one_hot['color_D']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['color/weight_E']=diamonds_test_one_hot['color_E']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['color/weight_F']=diamonds_test_one_hot['color_F']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['color/weight_G']=diamonds_test_one_hot['color_G']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['color/weight_H']=diamonds_test_one_hot['color_H']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['color/weight_I']=diamonds_test_one_hot['color_I']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['color/weight_J']=diamonds_test_one_hot['color_J']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_I1']=diamonds_test_one_hot['clarity_I1']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_IF']=diamonds_test_one_hot['clarity_IF']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_SI1']=diamonds_test_one_hot['clarity_SI1']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_SI2']=diamonds_test_one_hot['clarity_SI2']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_VS1']=diamonds_test_one_hot['clarity_VS1']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_VS2']=diamonds_test_one_hot['clarity_VS2']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_VVS1']=diamonds_test_one_hot['clarity_VVS1']/diamonds_test_one_hot['carat']
diamonds_test_one_hot['clarity/weight_VVS2']=diamonds_test_one_hot['clarity_VVS2']/diamonds_test_one_hot['carat']
diamonds_test_one_hot

,carat,depth,table,x,y,z,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,...,color/weight_I,color/weight_J,clarity/weight_I1,clarity/weight_IF,clarity/weight_SI1,clarity/weight_SI2,clarity/weight_VS1,clarity/weight_VS2,clarity/weight_VVS1,clarity/weight_VVS2
0,0.79,62.7,60.0,5.82,5.89,3.67,0.0,0.0,1.0,0.0,...,0.000000,0.000000,0.0,0.0,1.265823,0.000000,0.000000,0.000000,0.0,0.0
1,1.20,61.0,57.0,6.81,6.89,4.18,0.0,0.0,0.0,0.0,...,0.000000,0.833333,0.0,0.0,0.000000,0.000000,0.833333,0.000000,0.0,0.0
2,1.57,62.2,61.0,7.38,7.32,4.57,0.0,0.0,1.0,0.0,...,0.000000,0.000000,0.0,0.0,0.636943,0.000000,0.000000,0.000000,0.0,0.0
3,0.90,63.8,54.0,6.09,6.13,3.90,0.0,0.0,1.0,0.0,...,0.000000,0.000000,0.0,0.0,1.111111,0.000000,0.000000,0.000000,0.0,0.0
4,0.50,62.9,58.0,5.05,5.09,3.19,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,2.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,0.57,61.9,56.0,5.35,5.32,3.30,0.0,0.0,1.0,0.0,...,0.000000,0.000000,0.0,0.0,1.754386,0.000000,0.000000,0.000000,0.0,0.0
13481,0.71,62.2,55.0,5.71,5.73,3.56,0.0,0.0,0.0,0.0,...,1.408451,0.000000,0.0,0.0,0.000000,0.000000,0.000000,1.408451,0.0,0.0
13482,0.70,61.6,55.0,5.75,5.71,3.53,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,1.428571,0.000000,0.0,0.0
13483,0.70,58.8,57.0,5.85,5.89,3.45,0.0,0.0,0.0,1.0,...,0.000000,0.000000,0.0,0.0,0.000000,1.428571,0.000000,0.000000,0.0,0.0
13484,0.40,62.4,55.0,4.70,4.73,2.94,0.0,0.0,0.0,0.0,...,2.500000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,2.5

In [31]:
diamonds_test_one_hot = diamonds_test_one_hot.drop(columns=['clarity_I1',
'clarity_IF',
'clarity_SI1',
'clarity_SI2',
'clarity_VS1',
'clarity_VS2',
'clarity_VVS1',
'clarity_VVS2',
'color_D',
'color_E',
'color_F',
'color_G',
'color_H',
'color_I',
'color_J'], axis=1)

diamonds_test_one_hot

,carat,depth,table,x,y,z,cut,color/weight_D,color/weight_E,color/weight_F,...,color/weight_I,color/weight_J,clarity/weight_I1,clarity/weight_IF,clarity/weight_SI1,clarity/weight_SI2,clarity/weight_VS1,clarity/weight_VS2,clarity/weight_VVS1,clarity/weight_VVS2
0,0.79,62.7,60.0,5.82,5.89,3.67,3,0.0,0.000000,1.265823,...,0.000000,0.000000,0.0,0.0,1.265823,0.000000,0.000000,0.000000,0.0,0.0
1,1.20,61.0,57.0,6.81,6.89,4.18,1,0.0,0.000000,0.000000,...,0.000000,0.833333,0.0,0.0,0.000000,0.000000,0.833333,0.000000,0.0,0.0
2,1.57,62.2,61.0,7.38,7.32,4.57,5,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.636943,0.000000,0.000000,0.000000,0.0,0.0
3,0.90,63.8,54.0,6.09,6.13,3.90,3,0.0,0.000000,1.111111,...,0.000000,0.000000,0.0,0.0,1.111111,0.000000,0.000000,0.000000,0.0,0.0
4,0.50,62.9,58.0,5.05,5.09,3.19,3,0.0,0.000000,2.000000,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,2.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,0.57,61.9,56.0,5.35,5.32,3.30,1,0.0,1.754386,0.000000,...,0.000000,0.000000,0.0,0.0,1.754386,0.000000,0.000000,0.000000,0.0,0.0
13481,0.71,62.2,55.0,5.71,5.73,3.56,1,0.0,0.000000,0.000000,...,1.408451,0.000000,0.0,0.0,0.000000,0.000000,0.000000,1.408451,0.0,0.0
13482,0.70,61.6,55.0,5.75,5.71,3.53,1,0.0,0.000000,1.428571,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,1.428571,0.000000,0.0,0.0
13483,0.70,58.8,57.0,5.85,5.89,3.45,3,0.0,0.000000,1.428571,...,0.000000,0.000000,0.0,0.0,0.000000,1.428571,0.000000,0.000000,0.0,0.0
13484,0.40,62.4,55.0,4.70,4.73,2.94,1,0.0,0.000000,0.000000,...,2.500000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,2.5

In [32]:
diamonds_test_one_hot['volume'] = diamonds_test_one_hot['x']*diamonds_test_one_hot['y']*diamonds_test_one_hot['z']
diamonds_test_one_hot

,carat,depth,table,x,y,z,cut,color/weight_D,color/weight_E,color/weight_F,...,color/weight_J,clarity/weight_I1,clarity/weight_IF,clarity/weight_SI1,clarity/weight_SI2,clarity/weight_VS1,clarity/weight_VS2,clarity/weight_VVS1,clarity/weight_VVS2,volume
0,0.79,62.7,60.0,5.82,5.89,3.67,3,0.0,0.000000,1.265823,...,0.000000,0.0,0.0,1.265823,0.000000,0.000000,0.000000,0.0,0.0,125.806866
1,1.20,61.0,57.0,6.81,6.89,4.18,1,0.0,0.000000,0.000000,...,0.833333,0.0,0.0,0.000000,0.000000,0.833333,0.000000,0.0,0.0,196.129362
2,1.57,62.2,61.0,7.38,7.32,4.57,5,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.636943,0.000000,0.000000,0.000000,0.0,0.0,246.878712
3,0.90,63.8,54.0,6.09,6.13,3.90,3,0.0,0.000000,1.111111,...,0.000000,0.0,0.0,1.111111,0.000000,0.000000,0.000000,0.0,0.0,145.593630
4,0.50,62.9,58.0,5.05,5.09,3.19,3,0.0,0.000000,2.000000,...,0.000000,0.0,0.0,0.000000,0.000000,2.000000,0.000000,0.0,0.0,81.997355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,0.57,61.9,56.0,5.35,5.32,3.30,1,0.0,1.754386,0.000000,...,0.000000,0.0,0.0,1.754386,0.000000,0.000000,0.000000,0.0,0.0,93.924600
13481,0.71,62.2,55.0,5.71,5.73,3.56,1,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.000000,0.000000,0.000000,1.408451,0.0,0.0,116.477148
13482,0.70,61.6,55.0,5.75,5.71,3.53,1,0.0,0.000000,1.428571,...,0.000000,0.0,0.0,0.000000,0.000000,1.428571,0.000000,0.0,0.0,115.898725
13483,0.70,58.8,57.0,5.85,5.89,3.45,3,0.0,0.000000,1.428571,...,0.000000,0.0,0.0,0.000000,1.428571,0.000000,0.000000,0.0,0.0,118.874925
13484,0.40,62.4,55.0,4.70,4.73,2.94,1,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,2.5,65.359140

In [33]:
export_train = diamonds_one_hot.to_csv('./../data/training_label_and_onehot_no_cities_operations_vol.csv', index=False)

In [34]:
export_test = diamonds_test_one_hot.to_csv('./../data/diamonds_test_label_and_onehot_no_cities_operations_vol.csv', index=False)