In [1]:
#importo las librerias necesarias

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [7]:
#cargo el dataset de training y el de test

df_training = pd.read_csv('./data/training_one_hot.csv')
df_test = pd.read_csv('./data/diamonds_test_one_hot.csv')
df_training

,price,carat,depth,table,x,y,z,city_Amsterdam,city_Antwerp,city_Dubai,...,color_F,color_G,color_H,color_I,color_J,cut_Fair,cut_Good,cut_Ideal,cut_Premium,cut_Very Good
0,4268,1.21,62.4,58.0,6.83,6.79,4.25,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,3513,1.02,61.6,58.0,6.40,6.35,3.93,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,1792,0.77,62.3,58.0,5.86,5.80,3.63,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,7553,1.51,59.6,60.0,7.58,7.48,4.49,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,1176,0.57,60.2,62.0,5.40,5.33,3.23,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,1019,0.57,59.5,57.0,5.46,5.42,3.24,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
40451,6096,1.44,63.2,55.0,7.21,7.18,4.54,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
40452,3459,1.02,61.2,56.0,6.47,6.50,3.97,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
40453,4428,1.28,61.6,57.0,6.93,6.96,4.28,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
40454,6299,1.54,61.6,55.0,7.43,7.40,4.57,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [8]:
# Features + target

X = df_training[['carat',
                    'depth',
                    'table',
                    'x',
                    'y',
                    'z',
                    'city_Amsterdam',
                    'city_Antwerp',
                    'city_Dubai',
                    'city_Kimberly',
                    'city_Las Vegas',
                    'city_London',
                    'city_Luxembourg',
                    'city_Madrid',
                    'city_New York City',
                    'city_Paris',
                    'city_Surat',
                    'city_Tel Aviv',
                    'city_Zurich',
                    'clarity_I1',
                    'clarity_IF',
                    'clarity_SI1',
                    'clarity_SI2',
                    'clarity_VS1',
                    'clarity_VS2',
                    'clarity_VVS1',
                    'clarity_VVS2',
                    'color_D',
                    'color_E',
                    'color_F',
                    'color_G',
                    'color_H',
                    'color_I',
                    'color_J',
                    'cut_Fair',
                    'cut_Good',
                    'cut_Ideal',
                    'cut_Premium',
                    'cut_Very Good']]
y = pd.get_dummies(df_training[['price']], drop_first=True)
print(X.shape,y.shape)

(40455, 39) (40455, 1)

In [9]:
# Train + test

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Scaling - RobustScaler
scaler = StandardScaler()
scaled_data_rs = scaler.fit_transform(X_train)
scaled_data_rs
scaled_data_test = scaler.transform(X_test)
scaled_data_test

In [ ]:
regressor =  LinearRegression()

In [ ]:
hyperparameters = regressor.get_params()
model = regressor.fit(X_train, y_train)

In [ ]:
diamond = pd.read_csv('./data/diamonds_test.csv')
diamond

In [ ]:
diamond_test = diamond[["carat","depth","table","x","y","z"]]
diamond_test

In [ ]:
X_test.columns == diamond_test.columns

In [ ]:
y_pred = model.predict(X_test)

print('Model:', regressor, '\n')
print('Model hyperparameters:', hyperparameters, '\n')
#print('Ground truth target:', y_test, '\n')
print('Predicted target:', y_pred, '\n')

In [ ]:
y_pred.shape

In [ ]:
type(y_pred)

In [ ]:
r2_ = model.score(X_test, y_test)
r2_

In [ ]:
v = pd.DataFrame(y_pred)
v.columns
type(v)
len(v)

In [ ]:
y_pred

In [ ]:
len(diamond_test)

In [ ]:
y_hat = model.predict(diamond_test)

In [ ]:
y_hat.shape

In [ ]:
y_hat

In [ ]:
type(y_hat)

In [ ]:
df_pred = pd.DataFrame(data=y_hat)
df_pred

In [ ]:
df_pred = df_pred.reset_index(drop=True)
df_pred

In [ ]:
type(df_pred)

In [ ]:

df_rename = df_pred.rename(columns={"index": "id", "o": "price"})
df_rename

In [ ]:
final_prediction = df_rename.rename(columns={df_rename.columns[1]: "price" })
final_prediction

In [ ]:
export = final_prediction.to_csv('./data/first_test.csv', index=False)

In [ ]:
pd.read_csv('./data/first_test.csv').head()